### ISSUE TITLE
art.scnassets missing

### ISSUE THREAD

**Issue by hkortier** [PyojinKim/ARKit-Data-Logger#1]
Unfortunately a file is missing and required for building:

> error: Build input file cannot be found: '/Users/.../ARKit-Data-Logger/ARKit-Data-Logger/art.scnassets' (in target 'ARKit-Data-Logger' from project 'ARKit-Data-Logger')

**Comment by PyojinKim** [comment]
Sorry for a late reply.
You can just remove art.scnassets, then Xcode can build successfully.
